// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/card/sk-card.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync(".sk-card {\n  background: var(--sk-surface-card);\n  border: 2px solid var(--sk-border-default);\n  border-radius: var(--sk-radius-lg);\n\n  color: var(--sk-fg-body);\n  padding: var(--sk-space-7);\n\n  transition: border-color var(--sk-motion-duration-fast) var(--sk-motion-ease-out);\n}\n\n.sk-card--inset {\n  background: var(--sk-surface-input);\n  border-color: var(--sk-border-default);\n}\n\n.sk-card--blue {\n  background: var(--sk-surface-tint-sky);\n  border-color: var(--sk-border-tint-sky);\n}\n.sk-card--blue:hover {\n  border-color: var(--sk-color-blue);\n}\n\n.sk-card--purple {\n  background: var(--sk-surface-tint-lilac);\n  border-color: var(--sk-border-tint-lilac);\n}\n.sk-card--purple:hover {\n  border-color: var(--sk-color-purple);\n}");
export default sheet;
