// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/section-banner/sk-section-banner.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkSectionBannerHTML = "<div class=\"sk-section-banner sk-section-banner--neutral\"><span class=\"sk-section-banner__dot\" aria-hidden=\"true\">●</span><span class=\"sk-section-banner__label\">Section label</span></div>";
export const SkSectionBannerNeutralHTML = "<div class=\"sk-section-banner sk-section-banner--neutral\"><span class=\"sk-section-banner__dot\" aria-hidden=\"true\">●</span><span class=\"sk-section-banner__label\">Section label</span></div>";
export const SkSectionBannerPurpleHTML = "<div class=\"sk-section-banner sk-section-banner--purple\"><span class=\"sk-section-banner__dot\" aria-hidden=\"true\">●</span><span class=\"sk-section-banner__label\">Section label</span></div>";
export const SkSectionBannerGreenHTML = "<div class=\"sk-section-banner sk-section-banner--green\"><span class=\"sk-section-banner__dot\" aria-hidden=\"true\">●</span><span class=\"sk-section-banner__label\">Section label</span></div>";
