// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/card/sk-card.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkCardHTML = "<article class=\"sk-card\">Card content</article>";
export const SkCardBlueHTML = "<article class=\"sk-card sk-card--blue\">Card content</article>";
export const SkCardPurpleHTML = "<article class=\"sk-card sk-card--purple\">Card content</article>";
export const SkCardInsetHTML = "<article class=\"sk-card sk-card--inset\">Card content</article>";
