// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/card/sk-card.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkCardHTML = "<article class=\"sk-card\">Card content</article>";
export const SkCardBlueHTML = "<article class=\"sk-card sk-card--blue\">Card content</article>";
export const SkCardPurpleHTML = "<article class=\"sk-card sk-card--purple\">Card content</article>";
export const SkCardInsetHTML = "<article class=\"sk-card sk-card--inset\">Card content</article>";
export const SkCardStatusNeutralHTML = "<article class=\"sk-card sk-card--status-neutral\">Card content</article>";
export const SkCardStatusInfoHTML = "<article class=\"sk-card sk-card--status-info\">Card content</article>";
export const SkCardStatusSuccessHTML = "<article class=\"sk-card sk-card--status-success\">Card content</article>";
export const SkCardStatusAttentionHTML = "<article class=\"sk-card sk-card--status-attention\">Card content</article>";
export const SkCardStatusDangerHTML = "<article class=\"sk-card sk-card--status-danger\">Card content</article>";
export const SkCardStatusRecoveryHTML = "<article class=\"sk-card sk-card--status-recovery\">Card content</article>";
