// GENERATED by scripts/build-vue-types.mjs — DO NOT EDIT BY HAND.
// Regenerate: npx nx run elements:analyze && node scripts/build-vue-types.mjs
//
// Vue template types for the Spec Kitty custom elements (#81).
//
// OPT-IN. Reference this file from your project so it is not loaded for consumers who do not use
// Vue — it augments the 'vue' module, and a package that always did so would force a `vue`
// dependency on every consumer:
//
//     /// <reference types="@spec-kitty/elements/vue" />
//
// You still need one line of build configuration for SFCs. Full integration guide:
// https://github.com/spec-kitty/spec-kitty-design/blob/main/docs/consuming-from-vue.md

import type { DefineComponent, HTMLAttributes, ReservedProps } from 'vue';

type SkElement<P> = DefineComponent<P & Partial<HTMLAttributes> & ReservedProps>;

declare module 'vue' {
  export interface GlobalComponents {
    /**
     * A controlled, consumer-composed action row with optional native-route and flush presentation modes.
     *
     * Token dependencies: --sk-border-default, --sk-border-strong, --sk-border-width-1,
     * --sk-border-width-2, --sk-color-accent, --sk-fg-body, --sk-fg-default, --sk-fg-muted,
     * --sk-font-display, --sk-font-mono, --sk-font-sans, --sk-motion-duration-fast,
     * --sk-motion-ease-out, --sk-radius-md, --sk-space-1, --sk-space-2, --sk-space-3,
     * --sk-space-4, --sk-space-5, --sk-surface-card, --sk-surface-muted, --sk-surface-pill,
     * --sk-text-base, --sk-text-xs, --sk-weight-semibold.
     */
    'sk-action-row': SkElement<{
      /** Opaque native route destination. A non-blank value takes precedence over selectable-button mode. */
      'href'?: string | undefined;
      /** Optional compact presentation. Only `card` is supported; invalid values use the default row layout. */
      'layout'?: 'card' | undefined;
      /** Optional container-owned presentation. Only `flush` is supported; invalid values use the bordered row. */
      'presentation'?: 'flush' | undefined;
      /** Stable consumer-owned identifier included in activation requests. */
      'row-id'?: string | undefined;
      /** Enables the native primary trigger when `rowId` is non-empty. */
      'selectable'?: boolean;
      /** Consumer-controlled current-row presentation. Activation never changes this value. */
      'selected'?: boolean;
    }>;
    /**
     * A stateless page frame for personal navigation, contextual navigation, page heading, and content.
     *
     * Token dependencies: --sk-border-default, --sk-border-focus, --sk-border-strong,
     * --sk-border-width-1, --sk-border-width-2, --sk-layout-context-sidebar-width,
     * --sk-layout-personal-rail-width, --sk-space-3, --sk-space-4, --sk-space-12,
     * --sk-surface-card.
     */
    'sk-app-shell': SkElement<{
      /** Consumer-controlled responsive navigation state. The shell never changes this value. */
      'open'?: boolean;
      /** Enables an opt-in responsive layout. Omit it for the legacy responsive shell. */
      'presentation'?: 'compact' | 'rail-preserving' | undefined;
      /** Consumer trigger used only for accepted-Escape focus return. It must be actually assigned within this shell's compact-header slot and control a same-root target actually assigned within this shell's compact-navigation slot. */
      'compactTrigger'?: import('@spec-kitty/elements/dist/app-shell/sk-app-shell.js').SkAppShell["compactTrigger"];
    }>;
    /**
     * A controlled, property-fed bar chart for compact numeric comparisons.
     *
     * Token dependencies: --sk-border-default, --sk-border-strong, --sk-border-width-1,
     * --sk-border-focus, --sk-border-width-2, --sk-color-data-baseline,
     * --sk-color-data-grid, --sk-color-data-series-primary, --sk-fg-body, --sk-fg-default,
     * --sk-fg-muted, --sk-font-mono, --sk-font-sans,
     * --sk-motion-duration-fast, --sk-motion-ease-out, --sk-radius-md, --sk-radius-sm,
     * --sk-space-2, --sk-space-3, --sk-space-4, --sk-space-5, --sk-space-6,
     * --sk-space-10, --sk-surface-card, --sk-surface-muted, --sk-surface-pill,
     * --sk-text-sm, --sk-text-xs, --sk-weight-semibold.
     */
    'sk-bar-chart': SkElement<{
      /** Optional visible description associated with the chart figure. */
      'description'?: string;
      /** Accessible name for the chart figure. */
      'label'?: string;
      /** Enables native button surfaces that request datum selection. */
      'selectable'?: boolean;
      /** Controlled selected datum identifier. The component never mutates it. */
      'selected-id'?: string;
      /** Complete consumer-owned data series. Invalid series fail closed. */
      'series'?: import('@spec-kitty/elements/dist/bar-chart/sk-bar-chart.js').SkBarChart["series"];
    }>;
    /**
     * A blog preview card: thumbnail, eyebrow, title, excerpt, meta and a read-more link.
     *
     * It COMPOSES `sk-card`'s stylesheet rather than nesting the element, so the frame is authored
     * once in `sk-card.css` and this component's own sheet adds only blog layout — the contract its
     * CSS header has always described, now true of the element as well as the static form.
     */
    'sk-blog-card': SkElement<{
      /**
       * Alt text for the preview image. Set it whenever `thumbnail` is set.
       *
       * ONE WORD, and I walked into the reason twice. This was `thumbnailAlt`, which Lit maps to a
       * hyphenated `thumbnail-alt` attribute — and a hyphen is not a valid JS property key, so
       * `build-react-wrappers.mjs` refuses it: the emitted createElement props cannot carry the
       * key, and under ssrSafe (where React delivers first-render props as ATTRIBUTES) the value
       * would never reach the element. sk-ribbon-card hit this at #78 and its comment records it;
       * this component hit it anyway. `alt` is also the HTML attribute it feeds.
       */
      'alt'?: string | undefined;
      /** A short lead-in above the title, such as a category. */
      'eyebrow'?: string | undefined;
      /**
       * The preview image's URL. With none, no `<img>` is rendered at all — an empty one is a
       * broken-image icon rather than a neutral placeholder.
       */
      'thumbnail'?: string | undefined;
    }>;
    /**
     * A button, or a link styled as one.
     *
     * Set `href` and it renders an anchor; omit it and you get a button. That is not a
     * convenience — every use of this primitive in the demo pages is an `<a href>` styled as a
     * button, while the stories use `<button>`, so the catalogue already needs both and the class
     * list is identical either way.
     */
    'sk-button': SkElement<{
      /**
       * Shows a decorative activity cue via CSS alone. Purely presentational: this component
       * never sets, clears, or reads `disabled`/`aria-disabled` on account of `busy`, owns no
       * request/timer/announcement, and the accessible name is unchanged in either state — the
       * consumer's own request-handling code and disabling mechanism stay entirely its own.
       */
      'busy'?: boolean;
      /**
       * Disables the button. Ignored when `href` is set — a disabled link is not a thing HTML
       * has, and faking one with pointer-events hides it from assistive technology.
       */
      'disabled'?: boolean;
      /** When set, the element renders an anchor to this URL instead of a button. */
      'href'?: string | undefined;
      /** Accessible name forwarded unchanged to the real control. Required for the `icon` size. */
      'label'?: string | undefined;
      /** Size: `sm`, `icon`, or omit for the default. */
      'size'?: 'sm' | 'icon' | undefined;
      /**
       * Tone: `primary`, `secondary` or `ghost`. Omit for the unstyled base. An unknown value
       * renders the base button and warns rather than throwing.
       */
      'variant'?: 'primary' | 'secondary' | 'ghost' | undefined;
    }>;
    /** The card primitive — the first real component on the ADR-8 base layer. */
    'sk-card': SkElement<{
      /** Swaps the surface token for the inset (input) surface, for a card nested inside another. */
      'inset'?: boolean;
      /**
       * Operational status tone, orthogonal to `variant` — a card may carry both. The vocabulary is
       * `sk-status-indicator`'s; the card holds no domain mapping and never infers a tone. An unknown
       * value renders the base card and warns rather than throwing.
       */
      'status'?: 'neutral' | 'info' | 'success' | 'attention' | 'danger' | 'recovery' | undefined;
      /**
       * Accent colour. Omit for the default surface; an unknown value renders the base card and
       * warns rather than throwing.
       */
      'variant'?: 'blue' | 'purple' | undefined;
    }>;
    /**
     * A passive completion-state item for feature lists on marketing and reference pages.
     *
     * Put it inside a `<ul role="list">`. The element sets `role="listitem"` on itself, because a
     * custom element inside a `<ul>` is NOT a list item — the static form is a real `<li>`, and
     * this is the one place the two consumption paths differ structurally.
     */
    'sk-check-bullet': SkElement<{
      /** Decorative marker glyph. Defaults to the current state's marker; set it to override. */
      'icon'?: string | undefined;
      /** Read-only completion state. Omit for complete; unsupported values render as complete. */
      'state'?: 'complete' | 'pending' | undefined;
    }>;
    /**
     * A bounded, single-purpose confirmation dialog over the native `<dialog>`, opened via
     * `showModal()`.
     *
     * NO STRING HAS A DEFAULT (FR-001, FR-017). `dialogTitle`, `message`, `confirmLabel` and
     * `cancelLabel` are entirely consumer-supplied. Omitting one renders that node with nothing
     * substituted for it — never an English or any other library-authored literal — and logs a
     * one-time development warning naming the missing property. That is FR-018's guarantee,
     * proven in `fixtures/elements-behaviour/src/sk-confirm-dialog.test.ts` by a component-scoped
     * test asserting the rendered shadow tree carries zero bare user-visible text beyond the
     * exact supplied strings; that test is NOT a repo-wide gate (issue #286 owns building one).
     *
     * ONE REPORTING MECHANISM (FR-006). The element never fires a custom event for its outcome.
     * Every path — confirm, cancel, Escape, backdrop dismissal (when `backdrop-dismiss` is set),
     * and a programmatic `close()` with no explicit value — funnels through the native `<dialog>`
     * `close` event, read via `returnValue` (`'confirm' | 'cancel'`). Every path other than an
     * explicit confirm activation resolves `'cancel'` (FR-007) — the element defaults
     * `returnValue` to `'cancel'` before the dialog can be shown, so an unset programmatic close
     * can never be read back as an invented confirmation.
     *
     * THE ELEMENT PERFORMS NO MUTATION, REQUEST, OR NAVIGATION (FR-005). It reports what the user
     * did; the consumer decides what happens next, listening for the dialog's own `close` event:
     *
     * ```ts
     * const dialogEl = host.shadowRoot!.querySelector('[part="dialog"]') as HTMLDialogElement;
     * dialogEl.addEventListener('close', () => {
     *   if (dialogEl.returnValue === 'confirm') doTheThing();
     * });
     * ```
     *
     * STATIC FORM (FR-016). This component ships no `sk-confirm-dialog.markup.ts` and generates
     * no static `sk-confirm-dialog.html`/`index.ts` — `showModal()` has no server-rendered
     * equivalent, the same shape as `sk-notice` (#178). Authoring a static twin for the *stylesheet*
     * was always this component's own decision to make (matching #72/#73's decline, per
     * `adding-a-component.md`), not something gated by external ruling, and it declines one. #301
     * (the static-form-of-element-backed-CSS question) is CLOSED; its ruling shipped as ADR-15
     * (`docs/architecture/decisions/2026-09-10-15-static-form-of-element-backed-css.md`), still
     * `Proposed`, not ratified. ADR-15 rules on exactly three CSS construct kinds — a host-attribute
     * variant axis inside a host-owned `@container`, a host-owned `container-type`, and `::slotted()`
     * — and `sk-confirm-dialog.css` uses none of them: no `@container`, no `container-type`, no
     * `::slotted()`, and its one `:host` rule is unconditional, not an attribute-gated variant axis.
     * There is therefore no ruling to defer to, and none is needed — nothing about this stylesheet's
     * shape raises the shadow-vs-static divergence question ADR-15 exists to resolve.
     *
     * TEAM DELETION IS NEVER A DEMONSTRATED FLOW (FR-014). Whole-Team deletion is blocked upstream
     * (Team Kitty SaaS #1432); every example anywhere near this component uses membership
     * removal, leaving a team, or bearer-link revocation instead.
     *
     * Token dependencies: --sk-border-default, --sk-border-width-1, --sk-fg-body,
     * --sk-fg-default, --sk-font-sans, --sk-motion-duration-fast, --sk-motion-ease-out,
     * --sk-radius-lg, --sk-shadow-elev, --sk-space-2, --sk-space-3, --sk-space-4, --sk-space-5,
     * --sk-space-8, --sk-space-9, --sk-text-base, --sk-text-lg, --sk-weight-semibold (this
     * component's own sheet), plus whichever `--sk-*` tokens the composed `.sk-button` sheet
     * uses for the confirm/cancel controls.
     */
    'sk-confirm-dialog': SkElement<{
      /**
       * Whether clicking the dialog's own backdrop closes it. Defaults to `false`: a
       * destructive confirmation's safest default is to require an explicit control activation,
       * so an accidental click outside the dialog's content does nothing rather than silently
       * cancelling. When set, a backdrop click resolves `'cancel'` (FR-007).
       */
      'backdrop-dismiss'?: boolean;
      /** The cancel control's visible label. Required — no default (FR-001, FR-017). */
      'cancel-label'?: string | undefined;
      /** The confirm control's visible label. Required — no default (FR-001, FR-017). */
      'confirm-label'?: string | undefined;
      /**
       * The confirm control's `.sk-button` tone (`primary`, `secondary` or `ghost`). Omit for
       * the unstyled base button. The element never infers or applies a tone itself (FR-004) —
       * this is a style choice, not user-visible copy, so it is exempt from the no-defaults rule
       * and may reasonably be left unset by a consumer who wants the base button.
       */
      'confirm-variant'?: 'primary' | 'secondary' | 'ghost' | undefined;
      /**
       * The dialog's accessible name. Required — no default (FR-001, FR-017). Omitting it warns
       * and renders the title node with no text.
       */
      'dialog-title'?: string | undefined;
      /**
       * Which control receives focus when the dialog opens: `'confirm'` or `'cancel'`.
       * Defaults to `'cancel'`, the safe default for a destructive confirmation (FR-008). An
       * unknown value warns and falls back to `'cancel'`.
       */
      'initial-focus'?: 'confirm' | 'cancel';
      /**
       * The dialog's accessible description. Required — no default (FR-001, FR-017). Long
       * values scroll independently of the action row (FR-010).
       */
      'message'?: string | undefined;
      /**
       * Reflects the dialog's real open/closed state (ADR-11 SC-005). Read-only in practice —
       * set by the element itself from `showModal()` and the native `close` event — a consumer
       * should not assign it directly to open or close the dialog; call `showModal()` and the
       * dialog's own `close()` instead.
       */
      'open'?: boolean;
    }>;
    /** A labelled complementary landmark for consumer-owned selected-context content. */
    'sk-context-sidebar': SkElement<{
      /** Accessible name forwarded unchanged to the complementary landmark when nonblank. */
      'label'?: string | undefined;
    }>;
    /**
     * A non-editable exact-value field with a single native copy control and truthful inline results.
     *
     * The displayed string is the string sent to the Clipboard API. When clipboard access is not
     * available, the visible code is focused and selected for a manual system copy shortcut. The
     * component never executes, parses, validates, logs, or includes the value in its result event.
     *
     * Token dependencies: --sk-border-default, --sk-border-focus, --sk-border-width-1,
     * --sk-border-width-2, --sk-fg-body, --sk-fg-muted, --sk-font-mono, --sk-font-sans,
     * --sk-radius-md, --sk-space-2, --sk-space-3, --sk-surface-input, --sk-text-sm.
     */
    'sk-copy-field': SkElement<{
      /** Message shown when neither copying nor exact selection succeeded. */
      'failure-message'?: string;
      /** Accessible name for the native copy control. Blank values warn and use `Copy value`. */
      'label'?: string;
      /** Message shown when the visible value was selected for manual copying. */
      'manual-message'?: string;
      /** Message shown after the Clipboard API fulfills. Blank values use the default. */
      'success-message'?: string;
      /** Exact text displayed and offered for copying. The empty string disables the control. */
      'value'?: string;
    }>;
    /**
     * A compact consumer-supplied icon, initials, or short mark with explicit accessible naming.
     *
     * Token dependencies: --sk-border-default, --sk-border-width-1, --sk-font-sans,
     * --sk-on-tint-butter, --sk-radius-pill, --sk-radius-sm, --sk-space-1, --sk-space-5,
     * --sk-space-7, --sk-space-9, --sk-surface-tint-butter, --sk-text-xs, --sk-weight-bold.
     */
    'sk-entity-marker': SkElement<{
      /** Optional bordered presentation whose outer box is identical to the unbordered form. Only `true` is supported; invalid values render unbordered. */
      'border'?: 'true' | undefined;
      /** Accessible name for a meaningful mark. Empty or whitespace-only values make it decorative. */
      'label'?: string | undefined;
      /** Optional circular presentation. Only `circle` is supported; invalid values use the square shape. */
      'shape'?: 'circle' | undefined;
      /** Optional presentation size. Only `sm`/`lg` are supported; invalid values use the default size. */
      'size'?: 'sm' | 'lg' | undefined;
    }>;
    /**
     * An ordered chain of generic evidence stages composed from real `sk-metric` elements.
     *
     * The consumer owns stage order, identity, display formatting, and domain meaning. Valid supplied
     * strings and object references are preserved; invalid whole inputs fail closed.
     *
     * Token dependencies: --sk-border-strong, --sk-border-width-1, --sk-border-width-2,
     * --sk-fg-muted, --sk-fg-subtle, --sk-font-mono, --sk-font-sans, --sk-space-1,
     * --sk-space-2, --sk-space-3, --sk-space-4, --sk-space-10, --sk-text-sm,
     * --sk-text-xs.
     */
    'sk-evidence-chain': SkElement<{
      /**
       * Ordered consumer-supplied stages, assigned as a JavaScript property. Assign a new array
       * reference after changing the collection. Defaults to a frozen empty array.
       */
      'stages'?: import('@spec-kitty/elements/dist/evidence-chain/sk-evidence-chain.js').SkEvidenceChain["stages"];
    }>;
    /**
     * A feature card: an accented icon chip above a title and a short body.
     *
     * The icon, title and body are all slotted, because they are the consuming page's content. The
     * component owns the frame, the chip and the two colour axes — which are independent: `accent`
     * colours the chip, `variant` colours the card's border, and a card may have either, both or
     * neither.
     */
    'sk-feature-card': SkElement<{
      /**
       * Icon-chip colour: `yellow` (the default), `green` or `purple`. An unknown value uses the
       * default and warns.
       */
      'accent'?: 'yellow' | 'green' | 'purple' | undefined;
      /**
       * Border colour: `border-yellow`, `border-green` or `border-purple`. Omit for the default
       * neutral hairline. An unknown value renders the plain card and warns rather than throwing.
       */
      'variant'?: 'border-yellow' | 'border-green' | 'border-purple' | undefined;
    }>;
    /** A labelled text input that participates in a native form. */
    'sk-form-input': SkElement<{
      /** Forwarded to the inner control's `autocomplete` attribute, verbatim. */
      'autocomplete'?: string | null | undefined;
      /** Optional helper text rendered under the control and linked to it for screen readers. */
      'description'?: string;
      /** Excludes the field from submission and from user interaction. */
      'disabled'?: boolean;
      /**
       * A hint to the browser about the kind of on-screen keyboard to display. Hinting only — it
       * carries no validation semantics.
       */
      'inputmode'?: string | null | undefined;
      /**
       * Whether the field is showing an error. The element sets it from its own validity.
       * Assigning it directly paints the error state WITHOUT setting validity — the field looks
       * wrong and still submits — so use `setCustomError()` instead.
       */
      'invalid'?: boolean;
      /** The visible label. Also the accessible name, so it is not optional in practice. */
      'label'?: string;
      /**
       * The maximum value, for numeric and date/time input types. A string, matching the native
       * HTML attribute's own contract.
       */
      'max'?: string | null | undefined;
      /**
       * The minimum value, for numeric and date/time input types. A string, matching the native
       * HTML attribute's own contract.
       */
      'min'?: string | null | undefined;
      /**
       * The name submitted with the form value. Without it the field contributes no `FormData`
       * entry — though a required empty one still blocks its form.
       */
      'name'?: string;
      /**
       * A regular expression the value must match. Forwarded verbatim to the inner control; the
       * platform performs the match, this element does not re-validate it.
       */
      'pattern'?: string | null | undefined;
      /**
       * Placeholder text. Not a substitute for `label`: it disappears on input and is not a
       * reliable accessible name.
       */
      'placeholder'?: string;
      /**
       * Marks the field read-only. The value is still submitted with the form, unlike `disabled` —
       * but the field is barred from constraint validation, so a `required` read-only field never
       * blocks its form.
       */
      'readonly'?: boolean;
      /**
       * Marks the field required. An empty required field blocks submission and reports
       * `${label} is required`, or "This field is required" when `label` is empty.
       */
      'required'?: boolean;
      /**
       * The granularity the value must adhere to, for numeric and date/time input types. `"any"`
       * is a legal value the platform itself interprets.
       */
      'step'?: string | null | undefined;
      /** The native input type — `text`, `email`, `password`, and so on. */
      'type'?: string;
      /**
       * The current value, and what the form submits under `name` — unless `disabled`, which
       * submits nothing.
       */
      'value'?: string;
      /**
       * Suggested values shown in a native datalist alongside the input. A typed value matching no
       * option stays valid unless a forwarded constraint says otherwise — this is a suggestion
       * list, not a closed set.
       */
      'options'?: import('@spec-kitty/elements/dist/form-input/sk-form-input.js').SkFormInput["options"];
    }>;
    /** A labelled multi-line text control that participates in a native form. */
    'sk-form-textarea': SkElement<{
      /** Optional helper text rendered under the control and linked to it for screen readers. */
      'description'?: string;
      /** Excludes the field from submission and from user interaction. */
      'disabled'?: boolean;
      /**
       * Whether the field is showing an error. The element sets it from its own validity.
       * Assigning it directly paints the error state WITHOUT setting validity — the field looks
       * wrong and still submits — so use `setCustomError()` instead.
       */
      'invalid'?: boolean;
      /** The visible label. Also the accessible name, so it is not optional in practice. */
      'label'?: string;
      /**
       * The name submitted with the form value. Without it the field contributes no `FormData`
       * entry — though a required empty one still blocks its form.
       */
      'name'?: string;
      /**
       * Placeholder text. Not a substitute for `label`: it disappears on input and is not a
       * reliable accessible name.
       */
      'placeholder'?: string;
      /**
       * Marks the field required. An empty required field blocks submission and reports
       * `${label} is required`, or "This field is required" when `label` is empty.
       */
      'required'?: boolean;
      /** Visible height in text rows. */
      'rows'?: number;
      /**
       * The current value, and what the form submits under `name` — unless `disabled`, which
       * submits nothing.
       */
      'value'?: string;
    }>;
    /**
     * A responsive grid layout primitive.
     *
     * Bounded on purpose: it supports 2, 3 and 4 columns because that is what the blog listing and
     * reference pages need. It is not a general-purpose grid system. Use `::part(grid)` for layouts
     * outside that set rather than asking for another variant.
     */
    'sk-grid': SkElement<{
      /** Gap between items, in token steps: 3, 4 or 6. Omit for the default (4). */
      'gap'?: number | undefined;
      /**
       * Column count, as `cols-2`, `cols-3` or `cols-4`. Omit for a single column. An unknown
       * value renders the base grid and warns rather than throwing.
       */
      'variant'?: 'cols-2' | 'cols-3' | 'cols-4' | undefined;
    }>;
    /**
     * A generic supplied label and opaque display value with optional supporting annotation.
     *
     * The consumer owns all formatting and domain meaning. This element preserves valid strings
     * exactly and contributes a native definition relationship, not a section heading.
     *
     * Token dependencies: --sk-fg-default, --sk-fg-muted, --sk-font-mono, --sk-font-sans,
     * --sk-on-tint-butter, --sk-on-tint-mint, --sk-on-tint-sky, --sk-space-1,
     * --sk-space-2, --sk-space-3, --sk-space-4, --sk-text-2xl, --sk-text-sm,
     * --sk-text-xs, --sk-text-xl, --sk-weight-bold, --sk-weight-medium.
     */
    'sk-metric': SkElement<{
      /**
       * Optional supporting text, preserved exactly. Defaults to `''`; the annotation container is
       * omitted when this is empty.
       */
      'annotation'?: string;
      /**
       * Uses compact visual density when true, without changing content or semantics. Defaults to
       * `false`.
       */
      'compact'?: boolean;
      /**
       * Required opaque, preformatted display text, preserved exactly. Defaults to `''`; the
       * element never parses or rewrites it.
       */
      'display-value'?: string;
      /**
       * Required consumer-supplied label, preserved exactly. Defaults to `''`; blank values render
       * the unavailable state.
       */
      'label'?: string;
      /**
       * Generic presentation tone: `neutral` (the default), `info`, `success`, or `attention`.
       * Unsupported runtime values render the unavailable state.
       */
      'tone'?: 'neutral' | 'info' | 'success' | 'attention';
    }>;
    /** The navigation pill — a row of links that collapses to a hamburger and a panel. */
    'sk-nav-pill': SkElement<{
      /** Accessible name for the navigation landmark. */
      'label'?: string;
      /** Whether the navigation panel is open. Reflected as the `open` attribute. */
      'open'?: boolean;
    }>;
    /**
     * A block-level status message about a page or a region of it, announced at a politeness the
     * consumer chooses.
     *
     * Announcement is an explicit property, never a side effect of tone: a `danger` notice with
     * `announce="off"` is silent, and a `neutral` one with `announce="assertive"` interrupts. The
     * element owns no application state — the consumer decides whether a notice exists — and it has
     * no timer, no positioning and no stacking. It is not a toast.
     *
     * Token dependencies: --sk-border-default, --sk-border-focus, --sk-border-strong,
     * --sk-border-width-1, --sk-border-width-2, --sk-border-width-4, --sk-fg-body, --sk-font-sans,
     * --sk-motion-duration-fast, --sk-motion-ease-out, --sk-on-status-attention,
     * --sk-on-status-danger, --sk-on-status-info, --sk-on-status-neutral, --sk-on-status-recovery,
     * --sk-on-status-success, --sk-radius-md, --sk-radius-sm, --sk-space-1, --sk-space-2,
     * --sk-space-3, --sk-space-4, --sk-status-attention, --sk-status-danger, --sk-status-info,
     * --sk-status-neutral, --sk-status-recovery, --sk-status-success, --sk-surface-card,
     * --sk-text-base, --sk-text-lg, --sk-weight-semibold.
     */
    'sk-notice': SkElement<{
      /**
       * Announcement politeness. `off` (the default) renders no live region; `polite` renders
       * `role="status"`; `assertive` renders `role="alert"`. Independent of `tone`.
       */
      'announce'?: 'off' | 'polite' | 'assertive';
      /** Accessible name for the dismiss control. Defaults to `Dismiss notice`. */
      'dismiss-label'?: string;
      /** Whether to render the dismiss control. The element never removes itself when it is used. */
      'dismissible'?: boolean;
      /**
       * The message text. Changing it to a DIFFERENT value re-announces, when announcement is on.
       *
       * Re-setting it to the value it already holds announces nothing: Lit's default `hasChanged` is
       * `!==`, so an identical assignment produces no update and no DOM mutation for a screen reader
       * to notice. A dashboard that reports "Connection lost" twice in a row therefore announces it
       * once. If a repeat genuinely needs to be heard, the consumer must make the text differ — a
       * count or a timestamp — because an element that re-announced identical text on every
       * assignment would be unusable for the polling callers this is built for.
       *
       * A consumer that must announce a message which already exists when the notice is inserted
       * should insert the notice first and then assign this — a live region that enters the DOM
       * together with its content is not reliably announced, and the element cannot defer its own
       * first paint without a timer.
       */
      'message'?: string;
      /**
       * Presentation tone, from the library's one tone vocabulary. Unknown values render as
       * `neutral` without changing the visible message.
       */
      'tone'?: 'neutral' | 'info' | 'success' | 'attention' | 'danger' | 'recovery' | undefined;
    }>;
    /**
     * A stateless layout for consumer-owned page orientation, metadata, and actions.
     *
     * Two orthogonal axes. `density` changes how much room the header takes; `sticky` changes
     * whether it stays put while its scroll region scrolls. Neither implies the other, and the same
     * five slots resolve at either density — there is no second header to author and no second
     * markup path to drift.
     *
     * When `sticky` is set the HOST is the sticky box, so the header pins itself inside whatever
     * scroll container its surroundings provide. Two viewport thresholds return it to normal flow —
     * 720px of width and 480px of height — because a sticky header that eats a short viewport, or
     * that overlaps a focused control below it, is worse than no sticky header at all. Nothing is
     * dropped in that reflow.
     *
     * Consumers styling their own content under a sticky header should set
     * `scroll-margin-block-start: var(--sk-layout-page-header-sticky-scroll-margin)` on the
     * focusable elements in it, so a focused element scrolled into view is not obscured by the
     * header (WCAG 2.4.11).
     *
     * That token's DEFAULT VALUE covers ONE configuration: `density="compact"` laid out on a single
     * row, which is the header wider than 720px. It is derived from the header's own sticky offset
     * and compact block size rather than restated, so within that configuration it cannot drift.
     * Outside it the header is taller than the default and the consumer overrides the token — the
     * name stays the single place the value lives, which is the part of the contract that matters.
     * Two cases need the override, and the orthogonality above is why the first exists:
     *
     * - **Default density.** `sticky` without `density="compact"` is supported, and its height is
     *   entirely the consumer's slotted content — measured between 227px and 533px for one
     *   composition across two widths and two title lengths, against an 80px default. There is no
     *   honest derived number for it, so there is no second token: the consumer sets the value from
     *   their own header.
     * - **A stacked compact header.** Stacking is a CONTAINER query on the header's own width and the
     *   sticky drop is a MEDIA query on the viewport's, so they are not the same threshold: a 400px
     *   header column inside a 1400px viewport is sticky AND stacked at once — measured 96px against
     *   the same 80px default.
     *
     * The element does not measure its own live box to close that gap, because observing layout is
     * the class of behaviour it is deliberately barred from owning.
     *
     * The `sync` slot's contents are rendered verbatim. This element never starts a timer, reads a
     * clock, polls, observes scrolling, or computes a relative age: freshness belongs to the
     * consumer, which owns the timer and supplies the resulting string.
     */
    'sk-page-header': SkElement<{
      /**
       * Layout density, as `compact`. Omit for the default density. The compact form carries the
       * same five slots on a single row, with the actions region pinned and the text truncating
       * visually — the full text stays in the accessibility tree. An unknown value renders the
       * default density and warns rather than throwing.
       */
      'density'?: 'compact' | undefined;
      /**
       * Whether the header pins itself to the top of its scroll region. Independent of `density`:
       * a compact header need not stick and a sticky header need not be compact. Below 720px of
       * viewport width or 480px of viewport height the header returns to normal flow and stacks,
       * keeping the title, the metadata and the actions all present.
       */
      'sticky'?: boolean;
    }>;
    /** A labelled personal-navigation rail with consumer-owned controls in stable groups. */
    'sk-personal-rail': SkElement<{
      /** Accessible name forwarded unchanged to the navigation landmark when nonblank. */
      'label'?: string | undefined;
    }>;
    /**
     * A small inline label — a version tag, a status chip, or an eyebrow above a headline.
     *
     * `variant` sets the colour and `shape` sets the size; they are independent, so a tinted
     * eyebrow is expressible. The label is slotted, because the text is the consuming page's.
     */
    'sk-pill-tag': SkElement<{
      /** Shape: `eyebrow` for the larger, square-cornered lead-in label. Omit for the compact pill. */
      'shape'?: 'eyebrow' | undefined;
      /**
       * Operational status tone, orthogonal to `variant` and `shape` — a tag may carry any
       * combination. The vocabulary is `sk-status-indicator`'s; this element holds no domain mapping
       * and never infers a tone. An unknown value renders the base tag and warns rather than
       * throwing.
       */
      'status'?: 'neutral' | 'info' | 'success' | 'attention' | 'danger' | 'recovery' | undefined;
      /**
       * Colour: `green`, `purple`, `breaking` or `yellow`. Omit for the neutral tag. An unknown
       * value renders the base tag and warns rather than throwing.
       */
      'variant'?: 'green' | 'purple' | 'breaking' | 'yellow' | undefined;
    }>;
    /**
     * A card with an optional diagonal ribbon tab in its corner.
     *
     * The title and body are slotted, because they are the consuming page's content. The ribbon's
     * LABEL is a property rather than a slot — it is a short string the component positions and
     * rotates, and ADR-9 §4 took the same route for the form controls' `label`.
     *
     * The two colour axes are independent: `variant` tints the card's border, `accent` tints
     * the tab, and a card may use either, both or neither.
     */
    'sk-ribbon-card': SkElement<{
      /**
       * The ribbon's colour: `yellow` (the default), `green`, `purple`, `blue` or `red`. Ignored
       * when no `ribbon` label is set.
       */
      'accent'?: string | undefined;
      /**
       * The ribbon's label. The ribbon is rendered ONLY when this is set — an empty tab is a
       * coloured shape with no text, which reads as a bug rather than as a plain card.
       */
      'ribbon'?: string | undefined;
      /**
       * Border colour: `border-yellow`, `-green`, `-purple`, `-blue` or `-red`. Omit for the
       * default neutral hairline. An unknown value renders the plain card and warns.
       */
      'variant'?: string | undefined;
    }>;
    /**
     * A mono-caps banner that delineates a version or section block.
     *
     * Non-interactive by design: it has no hover, focus or disabled state, and the colour variant
     * IS the state. The label is slotted content, not a property — a banner's text is the
     * consuming page's, and hardcoding it in the component is what this element replaced.
     */
    'sk-section-banner': SkElement<{
      /**
       * Colour variant: `neutral` (the default), `purple` or `green`. An unknown value renders
       * the neutral banner and warns rather than throwing.
       */
      'variant'?: 'neutral' | 'purple' | 'green' | undefined;
    }>;
    /**
     * A presentational section heading whose outline level and supporting content are consumer-owned.
     *
     * Token dependencies: --sk-fg-default, --sk-fg-muted, --sk-font-display, --sk-font-mono,
     * --sk-font-sans, --sk-space-2, --sk-space-6, --sk-text-sm, --sk-text-xl, --sk-text-xs,
     * --sk-weight-medium, --sk-weight-semibold.
     */
    'sk-section-header': SkElement<{
      // no declared props
    }>;
    /**
     * A site footer: a brand column, two link columns, and a legal line.
     *
     * The element owns the structure — the grid, the `<nav>`s, the headings, the `<ul>`s, the divider
     * and the legal line. Text arrives as properties; only the link ITEMS are slotted, as `<li>`
     * elements that land directly inside the element's own `<ul>`.
     */
    'sk-site-footer': SkElement<{
      /** Heading for the first link column. */
      'headingOne'?: string | undefined;
      /** Heading for the second link column. */
      'headingTwo'?: string | undefined;
      /** The copyright line. Omit it and the divider above it is not rendered either. */
      'legal'?: string | undefined;
      /** Selects the compact, server-renderable presentation. Omit for the full presentation. */
      'presentation'?: 'full' | 'compact' | undefined;
      /** One sentence under the wordmark. */
      'tagline'?: string | undefined;
      /** The brand wordmark. */
      'wordmark'?: string | undefined;
    }>;
    /**
     * A consumer-labelled status with a presentation-only tone and decorative marker.
     *
     * Token dependencies: --sk-border-width-1, --sk-border-width-2, --sk-fg-body, --sk-fg-muted,
     * --sk-font-sans, --sk-motion-duration-slow, --sk-motion-ease-in-out, --sk-on-tint-butter,
     * --sk-on-tint-lilac, --sk-on-tint-mint, --sk-on-tint-rose, --sk-on-tint-sky, --sk-space-1,
     * --sk-space-2, --sk-text-sm.
     */
    'sk-status-indicator': SkElement<{
      /** Adds marker-only pulse presentation for consumer-supplied live activity. */
      'pulsing'?: boolean;
      /** Presentation tone. Unknown values render as `neutral` without changing the visible text. */
      'tone'?: 'neutral' | 'info' | 'success' | 'attention' | 'danger' | 'recovery' | undefined;
    }>;
    /** The scaffold element for the ADR-8 custom-element base layer. */
    'sk-stub': SkElement<{
      // no declared props
    }>;
    /**
     * A three-state theme-preference control that resolves System, Light, or Dark on the root.
     *
     * Consumer-supplied labels are required so the package never ships untranslated fallback copy.
     * If any label is absent or blank, the element renders no interactive control. The pre-paint
     * bootstrap is independent of this presentation and continues to provide system-default theming.
     *
     * Every control connected to one document shows one shared preference: a choice on any of them
     * selects it on all of them, and exactly one System listener exists while that preference is
     * System. A control connecting alongside another control adopts the page's current preference. A
     * control connecting alone re-reads storage and adopts it if it changed since the page last read
     * or saved it; otherwise, or when storage cannot be read, the page's own last preference resumes.
     * Either is skipped for a control given an explicit `preference` before connecting, which always
     * wins.
     */
    'sk-theme-toggle': SkElement<{
      /** Visible label for the Dark choice. */
      'dark-label'?: string;
      /** Visible legend and accessible name for the preference group. */
      'label'?: string;
      /** Visible label for the Light choice. */
      'light-label'?: string;
      /** Selected preference. Invalid attribute and property values safely become `system`. */
      'preference'?: 'system' | 'light' | 'dark';
      /** Visible label for the System choice. */
      'system-label'?: string;
    }>;
    /**
     * A controlled, property-fed line chart over a time axis whose missing intervals are drawn as
     * gaps and published as "No data".
     *
     * Every value is published persistently in a paired native table — the element's accessible
     * representation and its narrow-viewport treatment — so no meaning is hover-only. The graphic is
     * aria-hidden and carries no accessible content of its own. Selection is controlled: activation
     * requests a change and never makes one, and the only default action the element owns is moving
     * focus to the activated point, which a listener may cancel.
     *
     * Series are distinguished by three redundant channels — ink, dash pattern and marker shape —
     * because ink is the one of the three that collapses under forced-colors and in greyscale.
     *
     * Token dependencies: --sk-border-default, --sk-border-focus, --sk-border-strong,
     * --sk-border-width-1, --sk-border-width-2, --sk-chart-baseline, --sk-chart-dash-1,
     * --sk-chart-dash-2, --sk-chart-dash-3, --sk-chart-dash-4, --sk-chart-gap,
     * --sk-chart-gap-dash, --sk-chart-gap-fill, --sk-chart-grid, --sk-chart-plot-block-size,
     * --sk-chart-series-1, --sk-chart-series-2, --sk-chart-series-3, --sk-chart-series-4,
     * --sk-chart-stroke-width, --sk-fg-body, --sk-fg-default, --sk-fg-muted, --sk-font-mono,
     * --sk-font-sans, --sk-motion-duration-fast, --sk-motion-ease-out, --sk-radius-md,
     * --sk-radius-sm, --sk-space-1, --sk-space-2, --sk-space-3, --sk-space-4, --sk-space-5,
     * --sk-space-6, --sk-space-10, --sk-surface-card, --sk-surface-pill, --sk-text-sm,
     * --sk-text-xs, --sk-weight-medium.
     */
    'sk-time-series-chart': SkElement<{
      /** Optional visible description associated with the chart figure. */
      'description'?: string;
      /**
       * Consumer-supplied gap duration, in the same unit as the point timestamps, at or beyond which
       * a run with no observation earns a visible note. Zero, negative and non-finite values annotate
       * nothing. The element infers no threshold of its own.
       */
      'gap-threshold'?: number;
      /** Accessible name for the chart figure and the published table's caption. */
      'label'?: string;
      /** Enables native controls that request selection of a point. */
      'selectable'?: boolean;
      /** Controlled selected point identifier. The component never mutates it. */
      'selected-id'?: string;
      /** Complete consumer-owned series collection. An invalid collection fails closed. */
      'series'?: import('@spec-kitty/elements/dist/time-series-chart/sk-time-series-chart.js').SkTimeSeriesChart["series"];
    }>;
    /**
     * An aggregate route-by-time-bucket transition matrix with controlled route-selection intent.
     *
     * Token dependencies: --sk-border-default, --sk-border-focus, --sk-border-strong,
     * --sk-border-width-1, --sk-border-width-2, --sk-color-blue, --sk-color-green,
     * --sk-color-purple, --sk-color-red, --sk-fg-body, --sk-fg-default, --sk-fg-muted,
     * --sk-fg-on-card, --sk-font-mono, --sk-font-sans, --sk-radius-lg, --sk-radius-sm,
     * --sk-space-1, --sk-space-2, --sk-space-3, --sk-space-4, --sk-space-5,
     * --sk-space-6, --sk-space-10, --sk-space-12, --sk-surface-card,
     * --sk-surface-muted, --sk-surface-pill, --sk-text-lg, --sk-text-sm, --sk-text-xs,
     * --sk-weight-medium, --sk-weight-semibold.
     */
    'sk-transition-matrix': SkElement<{
      /** Optional consumer-authored explanation shown above the matrix. */
      'description'?: string;
      /** Enables route-selection intent without taking ownership of selection. */
      'selectable'?: boolean;
      /** Consumer-controlled selected route id. */
      'selected-route-id'?: string | undefined;
      /** Optional consumer-authored selectable-row instruction. */
      'selection-hint'?: string;
      /** Optional consumer-authored label for the reporting window. */
      'window-label'?: string;
      /** Consumer-labelled time buckets, assigned as a JavaScript property. */
      'columns'?: import('@spec-kitty/elements/dist/transition-matrix/sk-transition-matrix.js').SkTransitionMatrix["columns"];
      /** Aggregate transition routes, assigned as a JavaScript property. */
      'routes'?: import('@spec-kitty/elements/dist/transition-matrix/sk-transition-matrix.js').SkTransitionMatrix["routes"];
    }>;
  }
}

export {};
