// GENERATED by scripts/build-vue-types.mjs — DO NOT EDIT BY HAND.
// Regenerate: npx nx run elements:analyze && node scripts/build-vue-types.mjs
//
// Vue template types for the Spec Kitty custom elements (#81).
//
// OPT-IN. Reference this file from your project so it is not loaded for consumers who do not use
// Vue — it augments the 'vue' module, and a package that always did so would force a `vue`
// dependency on every consumer:
//
//     /// <reference types="@spec-kitty/elements/vue" />
//
// You still need one line of build configuration for SFCs. See docs/consuming-from-vue.md.

import type { HTMLAttributes, ReservedProps } from 'vue';

type SkElement<P> = P & Partial<HTMLAttributes> & ReservedProps;

declare module 'vue' {
  export interface GlobalComponents {
    /**
     * A blog preview card: thumbnail, eyebrow, title, excerpt, meta and a read-more link.
     */
    'sk-blog-card': SkElement<{
      /** Alt text for the preview image. Set it whenever `thumbnail` is set. */
      'alt'?: string | undefined;
      /** A short lead-in above the title, such as a category. */
      'eyebrow'?: string | undefined;
      /** The preview image's URL. With none, no `<img>` is rendered at all — an empty one is a */
      'thumbnail'?: string | undefined;
    }>;
    /**
     * A button, or a link styled as one.
     */
    'sk-button': SkElement<{
      /** Disables the button. Ignored when `href` is set — a disabled link is not a thing HTML */
      'disabled'?: boolean;
      /** When set, the element renders an anchor to this URL instead of a button. */
      'href'?: string | undefined;
      /** Size: `sm`, or omit for the default. */
      'size'?: 'sm' | undefined;
      /** Tone: `primary`, `secondary` or `ghost`. Omit for the unstyled base. An unknown value */
      'variant'?: 'primary' | 'secondary' | 'ghost' | undefined;
    }>;
    /**
     * The card primitive — the first real component on the ADR-8 base layer.
     */
    'sk-card': SkElement<{
      /** Swaps the surface token for the inset (input) surface, for a card nested inside another. */
      'inset'?: boolean;
      /** Accent colour. Omit for the default surface; an unknown value renders the base card and */
      'variant'?: 'blue' | 'purple' | undefined;
    }>;
    /**
     * A checked feature bullet, for the tick-lists on marketing and reference pages.
     */
    'sk-check-bullet': SkElement<{
      /** The tick glyph. Defaults to ✓; set it to use a different mark. */
      'icon'?: string | undefined;
    }>;
    /**
     * A feature card: an accented icon chip above a title and a short body.
     */
    'sk-feature-card': SkElement<{
      /** Icon-chip colour: `yellow` (the default), `green` or `purple`. An unknown value uses the */
      'accent'?: 'yellow' | 'green' | 'purple' | undefined;
      /** Border colour: `border-yellow`, `border-green` or `border-purple`. Omit for the default */
      'variant'?: 'border-yellow' | 'border-green' | 'border-purple' | undefined;
    }>;
    /**
     * A labelled text input that participates in a native form.
     */
    'sk-form-input': SkElement<{
      /** Optional helper text rendered under the control and linked to it for screen readers. */
      'description'?: string;
      /** Excludes the field from submission and from user interaction. */
      'disabled'?: boolean;
      /** Whether the field is showing an error. The element sets it from its own validity. */
      'invalid'?: boolean;
      /** The visible label. Also the accessible name, so it is not optional in practice. */
      'label'?: string;
      /** The name submitted with the form value. Without it the field contributes no `FormData` */
      'name'?: string;
      /** Placeholder text. Not a substitute for `label`: it disappears on input and is not a */
      'placeholder'?: string;
      /** Marks the field required. An empty required field blocks submission and reports */
      'required'?: boolean;
      /** The native input type — `text`, `email`, `password`, and so on. */
      'type'?: string;
      /** The current value, and what the form submits under `name` — unless `disabled`, which */
      'value'?: string;
    }>;
    /**
     * A labelled multi-line text control that participates in a native form.
     */
    'sk-form-textarea': SkElement<{
      /** Optional helper text rendered under the control and linked to it for screen readers. */
      'description'?: string;
      /** Excludes the field from submission and from user interaction. */
      'disabled'?: boolean;
      /** Whether the field is showing an error. The element sets it from its own validity. */
      'invalid'?: boolean;
      /** The visible label. Also the accessible name, so it is not optional in practice. */
      'label'?: string;
      /** The name submitted with the form value. Without it the field contributes no `FormData` */
      'name'?: string;
      /** Placeholder text. Not a substitute for `label`: it disappears on input and is not a */
      'placeholder'?: string;
      /** Marks the field required. An empty required field blocks submission and reports */
      'required'?: boolean;
      /** Visible height in text rows. */
      'rows'?: number;
      /** The current value, and what the form submits under `name` — unless `disabled`, which */
      'value'?: string;
    }>;
    /**
     * A responsive grid layout primitive.
     */
    'sk-grid': SkElement<{
      /** Gap between items, in token steps: 3, 4 or 6. Omit for the default (4). */
      'gap'?: number | undefined;
      /** Column count, as `cols-2`, `cols-3` or `cols-4`. Omit for a single column. An unknown */
      'variant'?: 'cols-2' | 'cols-3' | 'cols-4' | undefined;
    }>;
    /**
     * The navigation pill — a row of links that collapses to a hamburger and a panel.
     */
    'sk-nav-pill': SkElement<{
      /** Accessible name for the navigation landmark. */
      'label'?: string;
      /** Whether the navigation panel is open. Reflected as the `open` attribute. */
      'open'?: boolean;
    }>;
    /**
     * A small inline label — a version tag, a status chip, or an eyebrow above a headline.
     */
    'sk-pill-tag': SkElement<{
      /** Shape: `eyebrow` for the larger, square-cornered lead-in label. Omit for the compact pill. */
      'shape'?: 'eyebrow' | undefined;
      /** Colour: `green`, `purple`, `breaking` or `yellow`. Omit for the neutral tag. An unknown */
      'variant'?: 'green' | 'purple' | 'breaking' | 'yellow' | undefined;
    }>;
    /**
     * A card with an optional diagonal ribbon tab in its corner.
     */
    'sk-ribbon-card': SkElement<{
      /** The ribbon's colour: `yellow` (the default), `green`, `purple`, `blue` or `red`. Ignored */
      'accent'?: string | undefined;
      /** The ribbon's label. The ribbon is rendered ONLY when this is set — an empty tab is a */
      'ribbon'?: string | undefined;
      /** Border colour: `border-yellow`, `-green`, `-purple`, `-blue` or `-red`. Omit for the */
      'variant'?: string | undefined;
    }>;
    /**
     * A mono-caps banner that delineates a version or section block.
     */
    'sk-section-banner': SkElement<{
      /** Colour variant: `neutral` (the default), `purple` or `green`. An unknown value renders */
      'variant'?: 'neutral' | 'purple' | 'green' | undefined;
    }>;
    /**
     * A site footer: a brand column, two link columns, and a legal line.
     */
    'sk-site-footer': SkElement<{
      /** Heading for the first link column. */
      'headingOne'?: string | undefined;
      /** Heading for the second link column. */
      'headingTwo'?: string | undefined;
      /** The copyright line. Omit it and the divider above it is not rendered either. */
      'legal'?: string | undefined;
      /** One sentence under the wordmark. */
      'tagline'?: string | undefined;
      /** The brand wordmark. */
      'wordmark'?: string | undefined;
    }>;
    /**
     * The scaffold element for the ADR-8 custom-element base layer.
     */
    'sk-stub': SkElement<{
      // no attributes
    }>;
  }
}

export {};
