// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/section-banner/sk-section-banner.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync(":host {\n  display: inline-flex;\n}\n\n.sk-section-banner {\n  display: inline-flex;\n  align-items: center;\n  gap: var(--sk-space-3);\n  padding: var(--sk-space-2) var(--sk-space-4);\n  border-radius: var(--sk-radius-sm);\n  font-family: var(--sk-font-mono);\n  font-size: var(--sk-text-sm);\n  font-weight: var(--sk-weight-bold);\n  letter-spacing: 0.06em;\n  text-transform: uppercase;\n}\n\n.sk-section-banner--neutral {\n  background: var(--sk-surface-card);\n  color: var(--sk-fg-default);\n}\n\n.sk-section-banner--purple {\n  background: var(--sk-surface-tint-lilac);\n  color: var(--sk-on-tint-lilac);\n}\n\n.sk-section-banner--green {\n  background: var(--sk-surface-tint-mint);\n  color: var(--sk-on-tint-mint);\n}\n\n.sk-section-banner__dot {\n  font-size: var(--sk-text-base);\n}");
export default sheet;
