// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/grid/sk-grid.css
// Regenerate: node scripts/build-elements-css.mjs
import { unsafeCSS } from 'lit';
const cssText = ":host {\n  display: block;\n}\n\n.sk-grid {\n  display: grid;\n  grid-template-columns: 1fr;\n  gap: var(--sk-space-4);\n}\n\n.sk-grid--cols-2 {\n  grid-template-columns: repeat(2, 1fr);\n}\n\n.sk-grid--cols-3 {\n  grid-template-columns: repeat(3, 1fr);\n}\n\n.sk-grid--cols-4 {\n  grid-template-columns: repeat(4, 1fr);\n}\n\n.sk-grid--gap-3 {\n  gap: var(--sk-space-3);\n}\n\n.sk-grid--gap-4 {\n  gap: var(--sk-space-4);\n}\n\n.sk-grid--gap-6 {\n  gap: var(--sk-space-6);\n}\n\n@media (max-width: 720px) {\n  .sk-grid--cols-2,\n  .sk-grid--cols-3,\n  .sk-grid--cols-4 {\n    grid-template-columns: 1fr;\n  }\n}";
// Keep the browser/CSP contract native and synchronous. During an SSR import there is no
// CSSStyleSheet constructor, so Lit's DOM-free CSSResult carries the same trusted build output.
const sheet = typeof CSSStyleSheet === 'undefined' ? unsafeCSS(cssText) : new CSSStyleSheet();
if (typeof CSSStyleSheet !== 'undefined') {
  sheet.replaceSync(cssText);
}
export default sheet;
