// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/grid/sk-grid.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync(":host {\n  display: block;\n}\n\n.sk-grid {\n  display: grid;\n  grid-template-columns: 1fr;\n  gap: var(--sk-space-4);\n}\n\n.sk-grid--cols-2 {\n  grid-template-columns: repeat(2, 1fr);\n}\n\n.sk-grid--cols-3 {\n  grid-template-columns: repeat(3, 1fr);\n}\n\n.sk-grid--cols-4 {\n  grid-template-columns: repeat(4, 1fr);\n}\n\n.sk-grid--gap-3 {\n  gap: var(--sk-space-3);\n}\n\n.sk-grid--gap-4 {\n  gap: var(--sk-space-4);\n}\n\n.sk-grid--gap-6 {\n  gap: var(--sk-space-6);\n}\n\n@media (max-width: 720px) {\n  .sk-grid--cols-2,\n  .sk-grid--cols-3,\n  .sk-grid--cols-4 {\n    grid-template-columns: 1fr;\n  }\n}");
export default sheet;
