// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/entity-marker/sk-entity-marker.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync(":host {\n  display: inline-flex;\n}\n\n.sk-entity-marker {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n  min-width: var(--sk-space-7);\n  min-height: var(--sk-space-7);\n  padding: var(--sk-space-1);\n  background: var(--sk-surface-tint-butter);\n  border-radius: var(--sk-radius-sm);\n  color: var(--sk-on-tint-butter);\n  font-family: var(--sk-font-sans);\n  font-size: var(--sk-text-xs);\n  font-weight: var(--sk-weight-bold);\n}\n\n.sk-entity-marker__content {\n  display: inline-flex;\n  align-items: center;\n  justify-content: center;\n}");
export default sheet;
