// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/stub/sk-stub.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync("/* Same rules as Angular stub — tokens only, no hardcoded values */\n.sk-stub {\n  display: inline-flex;\n  align-items: center;\n  padding: var(--sk-space-2) var(--sk-space-4);\n  background: var(--sk-surface-card);\n  border: 1px solid var(--sk-border-default);\n  border-radius: var(--sk-radius-sm);\n}\n\n.sk-stub__label {\n  color: var(--sk-fg-default);\n  font-family: var(--sk-font-sans);\n  font-size: var(--sk-text-sm);\n}\n");
export default sheet;
