// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/stub/sk-stub.css
// Regenerate: node scripts/build-elements-css.mjs
import { unsafeCSS } from 'lit';
const cssText = ".sk-stub {\n  display: inline-flex;\n  align-items: center;\n  padding: var(--sk-space-2) var(--sk-space-4);\n  background: var(--sk-surface-card);\n  border: 1px solid var(--sk-border-default);\n  border-radius: var(--sk-radius-sm);\n}\n\n.sk-stub__label {\n  color: var(--sk-fg-default);\n  font-family: var(--sk-font-sans);\n  font-size: var(--sk-text-sm);\n}";
// Keep the browser/CSP contract native and synchronous. During an SSR import there is no
// CSSStyleSheet constructor, so Lit's DOM-free CSSResult carries the same trusted build output.
const sheet = typeof CSSStyleSheet === 'undefined' ? unsafeCSS(cssText) : new CSSStyleSheet();
if (typeof CSSStyleSheet !== 'undefined') {
  sheet.replaceSync(cssText);
}
export default sheet;
