// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/pill-tag/sk-pill-tag.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkPillTagHTML = "<span class=\"sk-pill-tag\">Label</span>";
export const SkPillTagGreenHTML = "<span class=\"sk-pill-tag sk-pill-tag--green\">Label</span>";
export const SkPillTagPurpleHTML = "<span class=\"sk-pill-tag sk-pill-tag--purple\">Label</span>";
export const SkPillTagBreakingHTML = "<span class=\"sk-pill-tag sk-pill-tag--breaking\">Label</span>";
export const SkPillTagYellowHTML = "<span class=\"sk-pill-tag sk-pill-tag--yellow\">Label</span>";
export const SkPillTagEyebrowHTML = "<span class=\"sk-pill-tag sk-pill-tag--eyebrow\">Label</span>";
