// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/grid/sk-grid.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkGridHTML = "<div class=\"sk-grid\">Grid content</div>";
export const SkGridCols2HTML = "<div class=\"sk-grid sk-grid--cols-2\">Grid content</div>";
export const SkGridCols3HTML = "<div class=\"sk-grid sk-grid--cols-3\">Grid content</div>";
export const SkGridCols4HTML = "<div class=\"sk-grid sk-grid--cols-4\">Grid content</div>";
export const SkGridGap3HTML = "<div class=\"sk-grid sk-grid--gap-3\">Grid content</div>";
export const SkGridGap6HTML = "<div class=\"sk-grid sk-grid--gap-6\">Grid content</div>";
