// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/grid/sk-grid.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkGridHTML = "<div class=\"sk-grid\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
export const SkGridCols2HTML = "<div class=\"sk-grid sk-grid--cols-2\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
export const SkGridCols3HTML = "<div class=\"sk-grid sk-grid--cols-3\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
export const SkGridCols4HTML = "<div class=\"sk-grid sk-grid--cols-4\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
export const SkGridGap3HTML = "<div class=\"sk-grid sk-grid--gap-3\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
export const SkGridGap4HTML = "<div class=\"sk-grid sk-grid--gap-4\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
export const SkGridGap6HTML = "<div class=\"sk-grid sk-grid--gap-6\"><div>Grid item 1</div><div>Grid item 2</div><div>Grid item 3</div></div>";
