// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/button/sk-button.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkButtonHTML = "<button class=\"sk-button\" type=\"button\">Label</button>";
export const SkButtonPrimaryHTML = "<button class=\"sk-button sk-button--primary\" type=\"button\">Label</button>";
export const SkButtonSecondaryHTML = "<button class=\"sk-button sk-button--secondary\" type=\"button\">Label</button>";
export const SkButtonGhostHTML = "<button class=\"sk-button sk-button--ghost\" type=\"button\">Label</button>";
export const SkButtonSmHTML = "<button class=\"sk-button sk-button--sm\" type=\"button\">Label</button>";
