// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/copy-field/sk-copy-field.css
// Regenerate: node scripts/build-elements-css.mjs
import { unsafeCSS } from 'lit';
const cssText = ":host {\n  box-sizing: border-box;\n  display: block;\n  container-type: inline-size;\n  inline-size: 100%;\n  max-inline-size: 100%;\n  min-inline-size: 0;\n}\n\n.sk-copy-field {\n  box-sizing: border-box;\n  display: grid;\n  grid-template-columns: minmax(0, 1fr) auto;\n  align-items: start;\n  gap: var(--sk-space-2) var(--sk-space-3);\n  min-inline-size: 0;\n  padding: var(--sk-space-3);\n  border: var(--sk-border-width-1) solid var(--sk-border-default);\n  border-radius: var(--sk-radius-md);\n  background: var(--sk-surface-input);\n  color: var(--sk-fg-body);\n  font-family: var(--sk-font-sans);\n}\n\n.sk-copy-field__value {\n  min-inline-size: 0;\n  white-space: pre-wrap;\n  overflow-wrap: anywhere;\n  font-family: var(--sk-font-mono);\n  font-size: var(--sk-text-sm);\n}\n\n.sk-copy-field__value:focus {\n  outline: var(--sk-border-width-2) solid var(--sk-border-focus);\n  outline-offset: var(--sk-border-width-2);\n}\n\n.sk-copy-field .sk-button {\n  transition: none;\n}\n\n.sk-copy-field__status {\n  grid-column: 1 / -1;\n  min-inline-size: 0;\n  color: var(--sk-fg-muted);\n  font-size: var(--sk-text-sm);\n  overflow-wrap: anywhere;\n}\n\n@container (max-inline-size: 20rem) {\n  .sk-copy-field {\n    grid-template-columns: minmax(0, 1fr);\n  }\n\n  .sk-copy-field .sk-button {\n    justify-self: end;\n  }\n}\n\n@media (forced-colors: active) {\n  .sk-copy-field {\n    border-color: CanvasText;\n    border-width: var(--sk-border-width-2);\n  }\n\n  .sk-copy-field__status {\n    color: CanvasText;\n  }\n}";
// Keep the browser/CSP contract native and synchronous. During an SSR import there is no
// CSSStyleSheet constructor, so Lit's DOM-free CSSResult carries the same trusted build output.
const sheet = typeof CSSStyleSheet === 'undefined' ? unsafeCSS(cssText) : new CSSStyleSheet();
if (typeof CSSStyleSheet !== 'undefined') {
  sheet.replaceSync(cssText);
}
export default sheet;
