// GENERATED by scripts/build-element-markup.mjs — DO NOT EDIT.
// Authored source: packages/elements/src/check-bullet/sk-check-bullet.markup.ts
// Regenerate: node scripts/build-element-markup.mjs
export const SkCheckBulletHTML = "<li class=\"sk-check-bullet\"><span class=\"sk-check-bullet__icon\" aria-hidden=\"true\">✓</span>Feature description here</li>";
