// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/check-bullet/sk-check-bullet.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync(":host {\n  display: block;\n}\n\n.sk-check-bullet {\n  display: flex;\n  align-items: flex-start;\n  gap: var(--sk-space-3);\n  list-style: none;\n  color: var(--sk-fg-default);\n  font-family: var(--sk-font-sans);\n  font-size: var(--sk-text-base);\n  line-height: 1.55;\n}\n\n.sk-check-bullet__icon {\n  color: var(--sk-on-tint-mint);\n  font-weight: var(--sk-weight-bold);\n  flex-shrink: 0;\n  margin-top: 0.1em;\n}\n\n.sk-check-bullet--pending .sk-check-bullet__icon {\n  color: var(--sk-fg-muted);\n}\n\n.sk-check-bullet__state {\n  position: absolute;\n  inline-size: var(--sk-border-width-1);\n  block-size: var(--sk-border-width-1);\n  overflow: hidden;\n  clip-path: inset(50%);\n  white-space: nowrap;\n}\n\n@media (forced-colors: active) {\n  .sk-check-bullet__icon,\n  .sk-check-bullet--pending .sk-check-bullet__icon {\n    color: CanvasText;\n    font-weight: var(--sk-weight-extrabold);\n  }\n}");
export default sheet;
