// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/check-bullet/sk-check-bullet.css
// Regenerate: node scripts/build-elements-css.mjs
const sheet = new CSSStyleSheet();
sheet.replaceSync("/* A custom element defaults to `display: inline`; `block` lets the wrapper's flex row lay out\n   and lets a consumer size the host. Inert in the static path, where the root IS the <li>. */\n:host {\n  display: block;\n}\n\n.sk-check-bullet {\n  display: flex;\n  align-items: flex-start;\n  gap: var(--sk-space-3);\n  list-style: none;\n  color: var(--sk-fg-default);\n  font-family: var(--sk-font-sans);\n  font-size: var(--sk-text-base);\n  line-height: 1.55;\n}\n\n.sk-check-bullet__icon {\n  color: var(--sk-color-green);\n  font-weight: var(--sk-weight-bold);\n  flex-shrink: 0;\n  margin-top: 0.1em;\n}\n");
export default sheet;
