// GENERATED by scripts/build-elements-css.mjs — DO NOT EDIT.
// Source of record: packages/styles/src/section-header/sk-section-header.css
// Regenerate: node scripts/build-elements-css.mjs
import { unsafeCSS } from 'lit';
const cssText = ":host {\n  display: block;\n}\n\n.sk-section-header {\n  display: grid;\n  grid-template-columns: minmax(0, 1fr) auto;\n  grid-template-areas:\n    \"eyebrow metadata\"\n    \"title action\"\n    \"description action\";\n  align-items: center;\n  column-gap: var(--sk-space-6);\n  row-gap: var(--sk-space-2);\n  color: var(--sk-fg-default);\n  font-family: var(--sk-font-sans);\n}\n\n.sk-section-header__eyebrow {\n  grid-area: eyebrow;\n  color: var(--sk-fg-muted);\n  font-family: var(--sk-font-mono);\n  font-size: var(--sk-text-xs);\n  font-weight: var(--sk-weight-medium);\n  text-transform: uppercase;\n}\n\n.sk-section-header__title {\n  grid-area: title;\n  min-width: 0;\n}\n\n.sk-section-header__title slot::slotted(*) {\n  margin: 0;\n  color: var(--sk-fg-default);\n  font-family: var(--sk-font-display);\n  font-size: var(--sk-text-xl);\n  font-weight: var(--sk-weight-semibold);\n}\n\n.sk-section-header__description {\n  grid-area: description;\n  min-width: 0;\n  color: var(--sk-fg-muted);\n  font-size: var(--sk-text-sm);\n}\n\n.sk-section-header__metadata {\n  grid-area: metadata;\n  justify-self: end;\n  color: var(--sk-fg-muted);\n  font-size: var(--sk-text-xs);\n}\n\n.sk-section-header__action {\n  grid-area: action;\n  align-self: end;\n  justify-self: end;\n}";
// Keep the browser/CSP contract native and synchronous. During an SSR import there is no
// CSSStyleSheet constructor, so Lit's DOM-free CSSResult carries the same trusted build output.
const sheet = typeof CSSStyleSheet === 'undefined' ? unsafeCSS(cssText) : new CSSStyleSheet();
if (typeof CSSStyleSheet !== 'undefined') {
  sheet.replaceSync(cssText);
}
export default sheet;
